services:
  #Service 1
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER: airflow
      - POSTGRES_PASSWORD: airflow
      - POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  #Service 2
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
